### ISSUE TITLE
How to analyze import behaviour

### ISSUE THREAD

**Issue by ursbraem** [fsaris/news_ttnewsimport#13]
Hi 

after adding page TS to tx_news, I was able to import a bunch of tt_news items into tx_news. But I have (at least) two Issues now I don't know how to debug.

* Nothing happening to categories. sys_category and sys_category_record_mm stay empty. (I only have one category and one subcategory in this example, located on the same page as the news items). 

* Not all items are imported. In the list module, I get a different count of the news items, but a diff of the entries rather shows that translations are being lost.

Can you give me some hints to fix this?
Thanks!
Urs

**Comment by velletti** [comment]
Today I had the same Problem:

i had 541 News in 8 language in tt_news table: 

some only default lang, som localized, some using -1 to show news in all languages and some exists only in one language and had no parent news.

And the (historical grown) data in tt_news was a real mess: 

there are entries with language -1 but have translations and i have entries with default language but with a parent id and at least localized entries with missing news parent!

finaly after import i just had 236 news in tx_news_domain_model_news 


Resultion:
i modified NewsImportService.php of original news extension 

### always store syslangauge uid !
+130: $news->setSysLanguageUid($importItem['sys_language_uid']);

### put entry only to persistance stack if it IS localized entry 
 
- 384: if ($importItem['sys_language_uid']) {
+ 384: if ($importItem['sys_language_uid'] && $importItem['l10n_parent'] > 0 ) {

### Fix Problem if tt_news entry is pointing to a missing parent
 change lines from 
-422 - 431 if ($parentNews !== NULL) {
			$importItem['import_id'] .= '|L:' . $importItem['sys_language_uid'];

			$news = $this->initializeNewsRecord($importItem);

			$this->hydrateNewsRecord($news, $importItem, $importItemOverwrite);

			$news->setSysLanguageUid($importItem['sys_language_uid']);
			$news->setL10nParent($parentNews->getUid());
		}

to 
              $importItem['import_id'] .= '|L:' . $importItem['sys_language_uid'];

		$news = $this->initializeNewsRecord($importItem);

		$this->hydrateNewsRecord($news, $importItem, $importItemOverwrite);

		$news->setSysLanguageUid($importItem['sys_language_uid']);
		if ($parentNews !== NULL) {

			$news->setL10nParent($parentNews->getUid());
		} else {
			$news->setL10nParent(0);

		}


When i now compare old with new with this query, nothing is missing ..:

select OLD.uid,OLD.title , OLD.sys_language_uid, OLD.l18n_parent, NEW.uid , NEW.sys_language_uid, NEW.l10n_parent 
from tt_news as OLD 
LEFT JOIN tx_news_domain_model_news NEW 
ON  NEW.import_id = OLD.uid 
where OLD.deleted = 0

questions or want the changed file ? just ask or send me an email: see profile 
https://github.com/velletti
