### ISSUE TITLE
Extension breaks on (empty) modifications

### ISSUE THREAD

**Issue by ursbraem** [fsaris/news_ttnewsimport#19]
I have two custom import jobs I have written based on the old version. Now I tried to add them to the new version, but as soon as I edit ext_tables.php (even saving without changes!), on re-installing the extension, the EM goes

```
Fatal error: Class 'Tx_News_Utility_ImportJob' not found in /Users/me/Sites/mysite/typo3conf/ext/news_ttnewsimport/ext_tables.php on line 6
```

I'm running this locally on MAMP, file permissions are good. Do you have an idea what this could be?
PS: I'll make a fork now and see how it goes if I install that

Cheers 
Urs

**Comment by ursbraem** [comment]
It's the same: I forked the repo, committed and pushed a modification (deleted an empty line), downloaded the zip from the github website and installed it - same error message as above.

**Comment by frans-beech-it** [comment]
What version of ext:news are you using? I expect 3.2.0. If you downgrade to 3.1.x it should work.

**Comment by ursbraem** [comment]
I see. What is the reason for that? 

And: I just noticed it still seems to work despite the error. Then again, my categories are now messed up. I guess I'll redo it with the downgrade and re-upgrade afterwards

**Comment by frans-beech-it** [comment]
ext:news 3.2.0 is has namespaced classes. That breaks currently with the importer

**Comment by ursbraem** [comment]
Ah I just realized!

**Comment by ursbraem** [comment]
It worked! Thanks! 

PS Maybe there are some issues with the categories. First, they were messed up (5 checked instead of none), now empty.

**Comment by frans-beech-it** [comment]
Just tested. Indeed you get an error, but after opening extension manager again the extension is installed. And also the importer works as expected.

**Comment by ursbraem** [comment]
Yes, I was just blocked out by the "Fatal" and didn't believe it would work despite it. Best regards

**Comment by frans-beech-it** [comment]
So issue can be closed?

**Comment by ursbraem** [comment]
For me yes, but from a global point of view this error shouldn't occur. Or put a warning note into the readme and the ext:news Readme? By the way: the plugin migrator is awesome!

**Comment by frans-beech-it** [comment]
You can thank Georg for the plugin migrator :)  The error is an core issue, not sure but should be fixed already there
