### ISSUE TITLE
Error in query executed by ./typo3/cli_dispatch.phpsh extbase ttnewspluginmigrate:removeOldPlugins delete=1

### ISSUE THREAD

**Issue by sr-amueller** [fsaris/news_ttnewsimport#20]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'delete='1' WHERE deleted=0 AND list_type="9" AND CType="list'' at line 1

I guess "delete" should be renamed to "deleted".

Kind regards
Andi

**Comment by beechit** [comment]
Hi Andi,

tnx for your feedback.
Could you create a pull request?

gr. Frans

**Comment by frans-beech-it** [comment]
Issue is already resolved in the meantime
