### ISSUE TITLE
Make it 7 compatible

### ISSUE THREAD

**Issue by Mabahe** [fsaris/news_ttnewsimport#25]
Could you create a branch for 7 compability? I already pushed one to my fork
https://github.com/Mabahe/news_ttnewsimport/tree/TYPO3_7

**Comment by fsaris** [comment]
I created the branch. Are you sure it is needed to switch to the ext:news namespaced classes? It should also still be working with the old classes, would like to keep it backwards compatible as long as possible. Then we only need to maintain only one branch.
