### ISSUE TITLE
Undefined class constant 'MAXIMUM_LINE_LENGTH' in news_ttnewsimport/Classes/Command/TtNewsPluginMigrateCommandController.php on line 78

### ISSUE THREAD

**Issue by seabass86** [fsaris/news_ttnewsimport#26]
Hey,

when I run:
./typo3/cli_dispatch.phpsh extbase ttnewspluginmigrate:check
I get the following fatal error:
Undefined class constant 'MAXIMUM_LINE_LENGTH' in /var/www/typo3dev/typo3conf/ext/news_ttnewsimport/Classes/Command/TtNewsPluginMigrateCommandController.php on line 78

Any idea on how to fix this?

Thank you!!
Sebastian

**Comment by frans-beech-it** [comment]
The constant was removed in core with https://review.typo3.org/#/c/30743/11 and replaced by `$this->output->getMaximumLineLength()`
