### ISSUE TITLE
Translation are not imported

### ISSUE THREAD

**Issue by demonking** [fsaris/news_ttnewsimport#27]
Hello,

i wanted to migrate tt_news to tx_news with translation, but somehow the l10n_parent id's are  wrong and also in the frontend are multiple news-entry in 1 language.

Typo3 upgrade from 4.5 to 6.2 :)

**Comment by ruudsilvrants** [comment]
Had the same issue when first importing the categories and afterwards directly the news items. The solution for me was refreshing the page after all categories are imported. Then going back to the news importer and then importing the news items.

**Comment by demonking** [comment]
@ruudsilvrants thx it works now ! 
@fsaris maybe we should make a FAQ for this kind of problems?
