### ISSUE TITLE
No News are imported, Importer says Done

### ISSUE THREAD

**Issue by digitalsun** [fsaris/news_ttnewsimport#29]
Unfortunatly the importer won't import any news. After clicking it says Done, but no news.

Typo3: 6.2.15
News: 2.2.24
 tt_news importer: 1.0.2

The import of categories worked, the news_import folder exists under fileadmin, what am I doign wrong?
Thanks for your help!

**Comment by digitalsun** [comment]
I found an entry in the error log:
Core/t3lib_db: Invalid database result detected: function TYPO3\\CMS\\Core\\Database\\DatabaseConnection->sql_free_result called from file po3conf/ext/news_ttnewsimport/Classes/Service/Import/TTNewsNewsDataProviderService.php in line 108. Use a devLog extension to get more details., referer: .../typo3/mod.php?M=web_NewsTxNewsM1&moduleToken=6ea2ae6bd27d4b0ff07984cd0fa0f9ed270b923a&id=1&

The developer log says -> extbase	-> The singleton "TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager" needs a prototype in "queryGenerator". This is often a bad code smell; often you rather want to inject a singleton.

Maybe this helps???

**Comment by digitalsun** [comment]
Didn't want to close the issue...

**Comment by fsaris** [comment]
is there no news imported at all? Could you maybe add 1 or 2 tt_news records here so we could test?

**Comment by frans-beech-it** [comment]
No response so guess the issue resolved itself
