### ISSUE TITLE
Plugin migration: `recursive` don't respect empty value

### ISSUE THREAD

**Issue by jousch** [fsaris/news_ttnewsimport#33]
Is there a special reason why there is a typecast to force int?

**Comment by fsaris** [comment]
not sure. Any reason why you would favor a empty string over 0?

**Comment by jousch** [comment]
empty string and 0 is a different behaviour: „Defined in typoscript“ vs „only 0 level/only this page"

**Comment by georgringer** [comment]
@fsaris IMO you can close this. news doesnt have a value "defined in typoscript" there. the plugin migration is not a 100% fully perfect thing to migrate everything.
