### ISSUE TITLE
How to keep the old tt_news uids

### ISSUE THREAD

**Issue by millemedia** [fsaris/news_ttnewsimport#37]
During mirgration the news importer changes the original uid and assigns a new one. In our case we need the old tt_news.uid because the site is listed on Google News and the uid is part of the url. Is there a possibility to keep the old uid's?

**Comment by frans-beech-it** [comment]
You could trick the importer a little to accomplish this. But it requires some manual SQL queries:

Insert select all tt_news records into tx_news_domain_model_news. 
You only need to insert the `uid` and `pid` + set `import_id` to `uid` and `import_source` to 'TT_NEWS_IMPORT';

Not tested:

```
INSERT INTO tx_news_domain_model_news (uid, pid, import_id, import_source) SELECT tt_news.uid, tt_news.pid, tt_news.uid, 'TT_NEWS_IMPORT' FROM tt_news;

```

After that just run the importer. The importer will fill the other fields and migrate images etc
