### ISSUE TITLE
Fatal error after install

### ISSUE THREAD

**Issue by sebastianschrama** [fsaris/news_ttnewsimport#39]
After installing the extension i get this error message: `Fatal error: Class 'Tx_News_Utility_ImportJob' not found in /vagrant/src/typo3conf/ext/news_ttnewsimport/ext_tables.php on line 6`

TYPO3 7.6.9
news 4.3.0
news_ttnewsimport 1.0.2

**Comment by fsaris** [comment]
Could you test current master? This should be fixed, but we didn't release a new version yet

**Comment by sebastianschrama** [comment]
Yes, that works. Thanks for your quick response!

**Comment by frans-beech-it** [comment]
your welcome :)
