### ISSUE TITLE
problem with plugin migration

### ISSUE THREAD

**Issue by p380** [fsaris/news_ttnewsimport#45]
I have a problem with plugin migration. 
When I run the following migration command, on the page the news does not appear. Display: "No news available" .
./typo3/cli_dispatch.phpsh extbase ttnewspluginmigrate:replace

They will only appear when I open and save the contents of the plugin in TYPO3 BE (without changes in plugin).

I have installed:
news 6.0.0
news_ttnewsimport 2.0.1

regards

**Comment by PascaleBeier** [comment]
@p380 did you find a solution? Currently having another issue with the plugin migration, see #47

@georgringer
